"""Add category and other missing columns to produce_listings

Revision ID: 6e813b9842ad
Revises: c92de5265454
Create Date: 2024-10-13 09:18:31.869366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e813b9842ad'
down_revision: Union[str, None] = 'c92de5265454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce_listings', sa.Column('category', sa.Enum('daily', 'weekly_monthly', 'dry_spices_nuts', 'grains', name='producecategory'), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produce_listings', 'category')
