"""Add minimum_bid_price and other missing columns to produce_listings

Revision ID: 85e7671293ec
Revises: 6e813b9842ad
Create Date: 2024-10-13 09:21:20.083090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85e7671293ec'
down_revision: Union[str, None] = '6e813b9842ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce_listings', sa.Column('minimum_bid_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produce_listings', 'minimum_bid_price')
