"""Add description and other missing columns to produce_listings

Revision ID: 93d6f77f7c1a
Revises: 6586b71b53d0
Create Date: 2024-10-14 08:53:20.225587

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93d6f77f7c1a"
down_revision: Union[str, None] = "6586b71b53d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("produce_listings", "govt_price")
    op.drop_column("produce_listings", "minimum_bid_price")
    op.drop_column("produce_listings", "photo_urls")
    op.drop_column("produce_listings", "category")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "produce_listings",
        sa.Column(
            "category",
            postgresql.ENUM(
                "DAILY",
                "WEEKLY_MONTHLY",
                "DRY_SPICES_NUTS",
                "GRAINS",
                name="producecategory",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "produce_listings",
        sa.Column("photo_urls", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "produce_listings",
        sa.Column(
            "minimum_bid_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "produce_listings",
        sa.Column(
            "govt_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
