"""Add initial data to role table

Revision ID: 6d26a9c5adfd
Revises: a32a82ebbf8c
Create Date: 2024-01-21 00:04:08.998655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d26a9c5adfd'
down_revision: Union[str, None] = 'a32a82ebbf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role_table = sa.table('role',
        sa.column('name', sa.String),
        sa.column('created_date', sa.DateTime),
        sa.column('updated_date', sa.DateTime)
    )

    op.bulk_insert(role_table,
        [
            {'name': 'Admin', 'created_date': '2023-10-05 17:28:57.254', 'updated_date': '2023-10-05 17:28:57.254'},
            {'name': 'Teacher', 'created_date': '2023-10-05 17:28:57.254', 'updated_date': '2023-10-05 17:28:57.254'},
            {'name': 'Student', 'created_date': '2023-10-05 17:28:57.254', 'updated_date': '2023-10-05 17:28:57.254'},
            {'name': 'Super Admin', 'created_date': '2023-10-05 17:28:57.254', 'updated_date': '2023-10-05 17:28:57.254'},
            {'name': 'Screening', 'created_date': '2023-10-05 17:28:57.254', 'updated_date': '2023-10-05 17:28:57.254'}
        ]
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role WHERE name IN ('Admin', 'Teacher', 'Student', 'Super Admin')")
    # ### end Alembic commands ###