"""4.3.1_Screening_1

Revision ID: bcc1fd9c3ce0
Revises: d055f44e7baa
Create Date: 2024-02-10 21:09:32.895454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc1fd9c3ce0'
down_revision: Union[str, None] = 'd055f44e7baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['institution_master.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['institution_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    op.create_foreign_key(None, 'configuration_history', 'institution_master', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'configuration_history', 'institution_master', ['created_by'], ['id'])
    op.alter_column('interview_master', 'percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('interview_master', 'marks',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('interview_master', 'max_marks',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('interview_master', 'skill_gap_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('training_course_user_mapping_course_id_fkey', 'training_course_user_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'training_course_user_mapping', 'training_course', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_master', sa.Column('screening_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_master', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_master', type_='foreignkey')
    op.drop_constraint(None, 'user_master', type_='foreignkey')
    op.drop_column('user_master', 'screening_id')
    op.drop_constraint(None, 'training_course_user_mapping', type_='foreignkey')
    op.create_foreign_key('training_course_user_mapping_course_id_fkey', 'training_course_user_mapping', 'training_course', ['course_id'], ['id'])
    op.drop_constraint(None, 'interview_master', type_='foreignkey')
    op.alter_column('interview_master', 'skill_gap_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('interview_master', 'max_marks',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('interview_master', 'marks',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('interview_master', 'percentage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'institution_master', type_='foreignkey')
    op.drop_constraint(None, 'configuration_history', type_='foreignkey')
    op.drop_constraint(None, 'configuration_history', type_='foreignkey')
    op.drop_table('screening_master')
    # ### end Alembic commands ###
