"""Initial Index

Revision ID: d055f44e7baa
Revises: b72e099c4854
Create Date: 2024-01-21 00:30:45.790401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd055f44e7baa'
down_revision: Union[str, None] = 'b72e099c4854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_configuration_history_created_by'), 'configuration_history', ['created_by'], unique=False)
    op.create_index(op.f('ix_interview_master_user_id'), 'interview_master', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_master_branch_id'), 'user_master', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_master_department_id'), 'user_master', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_master_institution_id'), 'user_master', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_master_institution_id'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_department_id'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_branch_id'), table_name='user_master')
    op.drop_index(op.f('ix_interview_master_user_id'), table_name='interview_master')
    op.drop_index(op.f('ix_configuration_history_created_by'), table_name='configuration_history')
    # ### end Alembic commands ###
