from .branch import Branch
from .country import Country
from .department import Department
from .institution_master import InstitutionMaster
from .role import Role
from .user_master import UserMaster
from .course import Course
from .company import Company
from .hard_skill import HardSkill
from .soft_skill import SoftSkill
from .working_role import WorkingRole
from .interview_master import InterviewMaster
from .report_point import ReportPoint
from .question import Question
from .institution_branch_mapping import InstitutionBranchMapping
from .branch_course_mapping import BranchCourseMapping
from .course_department_mapping import CourseDepartmentMapping
from .assignment import Assignment
from .question_bank import QuestionBankMaster
from .configuration_history import ConfigurationHistory
from .assignment_user_mapping import AssignmentUserMapping
from .institution_company_mapping import InstitutionCompanyMapping
from .institution_hard_skill_mapping import InstitutionHardSkillMapping
from .institution_soft_skill_mapping import InstitutionSoftSkillMapping
from .training_course import TrainingCourse
from .training_course_user_mapping import TrainingCourseUserMapping
from .screening_master import ScreeningMaster
from .assignment_results import AssignmentResults
from .entity_master import EntityMaster
from .entity_mapping import EntityMapping
from .placement_details import PlacementDetails
